from datetime import date

from app.core.db import SessionLocal
from app.models.agreement import AgreementTermsVersion

TERMS_V1 = """## StreamClip Co. Partner Terms (v1)

By accepting these terms, you authorize StreamClip Co. to:

1. Monitor your public livestreams on the platform(s) you've registered with us.
2. Identify, extract, and edit short clips from those streams.
3. Publish those clips, with attribution to your channel, on TikTok, Instagram Reels,
   YouTube Shorts, and X.
4. Add captions, hooks, titles, and hashtags to maximize reach.

In return, StreamClip Co. will pay you {rev_share_pct}% of net ad/creator-fund revenue
generated by clips of your content, paid out monthly, with a report of which clips
generated the revenue.

You may revoke this authorization at any time using the link included in every email
we send you, or by contacting partners@streamclip.co. Revocation stops all future
clipping and publishing of your content within 24 hours; it does not retract clips
already published, which you may separately request be taken down.

This is not a transfer of copyright — you retain all rights to your streams. This
agreement grants StreamClip Co. a non-exclusive, revocable license to clip and
publish, for as long as this agreement remains active.
"""


def main() -> None:
    db = SessionLocal()
    try:
        existing = (
            db.query(AgreementTermsVersion).filter(AgreementTermsVersion.version == "v1").first()
        )
        if existing:
            print("Terms v1 already seeded.")
            return
        db.add(AgreementTermsVersion(version="v1", effective_date=date.today(), body_markdown=TERMS_V1))
        db.commit()
        print("Seeded terms v1.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
