"""add stream session and viewer snapshot models

Revision ID: 5320850f9ab2
Revises: 141c8538e19e
Create Date: 2026-07-27 14:26:03.683228

"""
from alembic import op
import sqlalchemy as sa


revision = '5320850f9ab2'
down_revision = '141c8538e19e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_stream_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_stream_id')
    )
    op.create_table('viewer_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_session_id', sa.Integer(), nullable=False),
    sa.Column('viewer_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stream_session_id'], ['stream_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewer_snapshots')
    op.drop_table('stream_sessions')
    # ### end Alembic commands ###
