"""add agreement models

Revision ID: e054911ffd9e
Revises: 3a1d0e3aebbe
Create Date: 2026-07-27 10:44:24.083262

"""
from alembic import op
import sqlalchemy as sa


revision = 'e054911ffd9e'
down_revision = '3a1d0e3aebbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_terms_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('terms_version_id', sa.Integer(), nullable=False),
    sa.Column('rev_share_pct', sa.Float(), nullable=False),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_ip', sa.String(length=64), nullable=True),
    sa.Column('accepted_user_agent', sa.String(length=512), nullable=True),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['terms_version_id'], ['agreement_terms_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agreements')
    op.drop_table('agreement_terms_versions')
    # ### end Alembic commands ###
